data_analyzer/
    __init__.py
    src/
        objects/
            accelerometer.py
            gyroscope.py
            dataset.rpy
        data_processor.py
        data_analyzer.py
        terminal_driver.py
        controller.py