data_analyzer/
    __init__.py
    src/
        accel_processing/
            __init__.py
            accelerometer_controller.py
            accelerometer.py
        data_processing/
            __init__.py
            data_processing.py
        drivers/
            __init__.py
            csv_reader.py
        __init__.py
        dataset.py
        driver.py
        controller.py
